name: Desktop Artifacts(BOW)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 0.30.0)"
        required: false
        type: string
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Desktop Build (${{ matrix.name }})
    runs-on: namespace-profile-windows-8cpu
      # - ${{ matrix.os }}-with-cache
      # - nscloud-cache-size-50gb
      # - nscloud-cache-tag-agentsview-bow
    env:
      AGENTSVIEW_VERSION: ${{ inputs.version }}
      AGENTSVIEW_TARGET_TRIPLE: ${{ matrix.target_triple }}    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            bundle: nsis
            target_triple: ""
            artifact_name: agentsview-desktop-windows
            artifact_dir: desktop/src-tauri/target/release/bundle/nsis/
          # - name: macOS (aarch64)
          #   os: macos-15
          #   runner_arch: ARM64
          #   bundle: app
          #   target_triple: aarch64-apple-darwin
          #   artifact_name: agentsview-desktop-macos-aarch64
          #   artifact_dir: desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/build-desktop-artifact
        with:
          namespace-cache: ${{ matrix.name != 'Linux (arm64)' }}
          bundle: ${{ matrix.bundle }}
          target_triple: ${{ matrix.target_triple }}
          artifact_name: ${{ matrix.artifact_name }}
          artifact_dir: ${{ matrix.artifact_dir }}
